### ISSUE TITLE
Broken link on CSS style guidance

### ISSUE THREAD

**Issue by alexeybondarenko** [patternpack/patternpack-example-library#5]
Error: You do not have access to this repository.

https://bitbucket.org/slalom-consulting/dallas-css-standards

**Comment by marcelosomers** [comment]
Thanks! That was holdover from very early in this project. We probably just need to rethink the launch page when you use the example library.

**Comment by alexeybondarenko** [comment]
Have you any actual example or demo to see the generated docs?

**Comment by marcelosomers** [comment]
What specifically are you curious to know beyond running this example library?

**Comment by marcelosomers** [comment]
Fixed. @alexeybondarenko - I would still love to know what else you are curious about.
